"""Tests for tools/profile_engine.py - pure functions, no store, no I/O."""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
if str(REPO_ROOT / "tools") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "tools"))

from profile_engine import (arrival_label, build_brief, is_private,  # noqa: E402
                            route_preference, section_of, tier_for)


def test_tier_for_thresholds():
    assert tier_for(0) == "Silver"
    assert tier_for(2) == "Silver"
    assert tier_for(3) == "Gold"
    assert tier_for(7) == "Gold"
    assert tier_for(8) == "Platinum"
    assert tier_for(20) == "Platinum"


def test_tier_for_custom_thresholds():
    assert tier_for(4, platinum_min_stays=5, gold_min_stays=2) == "Gold"
    assert tier_for(5, platinum_min_stays=5, gold_min_stays=2) == "Platinum"


def test_is_private_matches_the_guardrail_regex():
    assert is_private("prefers to keep visits private", {}) is True
    assert is_private("", {"occasion": "no publicity please"}) is True
    assert is_private("a lovely, ordinary regular", {}) is False


def test_arrival_label_offsets():
    assert arrival_label(None) == "no upcoming stay"
    assert arrival_label(0) == "arriving today"
    assert arrival_label(1) == "arriving tomorrow"
    label = arrival_label(2, "2026-09-12")
    assert "D+2" in label and "Sep" in label


def test_route_preference_known_and_unknown_keys():
    sections = section_of({})
    section, text, trace = route_preference("drinks", "tawny port", sections)
    assert section == "fnb"
    assert text == "Drinks — tawny port"
    assert trace == "preference · drinks"
    # a key with no home in the default map lands in the front_office catch-all
    unknown_section, _, _ = route_preference("shoe_size", "10", sections)
    assert unknown_section == "front_office"


def test_section_of_extends_defaults_without_dropping_them():
    sections = section_of({"housekeeping": ["turndown_note"]})
    assert sections["turndown_note"] == "housekeeping"
    assert sections["drinks"] == "fnb"  # default still present


def _profile(**overrides) -> dict:
    base = {
        "guest_name": "Eleanor Ashby", "tier": "Platinum", "visits": 11,
        "room_type": "Meridian Suite", "arrival_offset": 2, "arrival_date": "2026-09-12",
        "preferences": {"room": "corner suite", "drinks": "tawny port", "occasion": "40th anniversary"},
        "history_note": "Long-time regulars.",
    }
    base.update(overrides)
    return base


def test_build_brief_every_line_has_a_trace():
    snippets = [{"id": "r-1", "source": "press", "headline": "Wine feature",
                "body": "A short mention.", "provenance": "public source — staff verified"}]
    brief = build_brief(_profile(), snippets, rules={"brief_daily": True, "vip_first": True},
                        sections_cfg={}, today=date(2026, 9, 10))
    all_lines = brief["housekeeping"] + brief["fnb"] + brief["front_office"]
    assert all_lines, "expected at least one desk line"
    for line in all_lines:
        assert line["trace"], f"line with no trace: {line}"
    assert brief["gm_line"].startswith("Eleanor Ashby —")
    assert "wine feature" in brief["gm_line"].lower()


def test_build_brief_no_research_says_so():
    brief = build_brief(_profile(), [], rules={"brief_daily": True, "vip_first": True},
                        sections_cfg={}, today=date(2026, 9, 10))
    assert "no research angle on file" in brief["gm_line"].lower()
    assert any("preference card and stay history alone" in t for t in brief["thinking"])


def test_build_brief_privacy_flag_changes_tone_and_thinking():
    private_profile = _profile(history_note="Guest prefers to keep visits private.")
    brief = build_brief(private_profile, [], rules={"brief_daily": True, "vip_first": True},
                        sections_cfg={}, today=date(2026, 9, 10))
    assert brief["private"] is True
    assert "greet by name in the suite" in brief["gm_line"].lower()


def test_build_brief_silver_does_not_get_the_vip_first_line():
    silver = _profile(tier="Silver", visits=1)
    brief = build_brief(silver, [], rules={"brief_daily": True, "vip_first": True},
                        sections_cfg={}, today=date(2026, 9, 10))
    stay_context = next(l["text"] for l in brief["front_office"] if l["trace"].startswith("rule"))
    assert "take their turn in the queue" in stay_context


def test_build_brief_stay_context_reads_as_plain_staff_guidance():
    """SIMULATION.md finding 3: the front-office "stay context" line used to
    read as leaked internal rule-engine text ("this brief would have
    generated by itself...", mid-sentence lowercase starts). It must read as
    a normal sentence a duty manager can act on."""
    brief = build_brief(_profile(), [], rules={"brief_daily": True, "vip_first": True},
                        sections_cfg={}, today=date(2026, 9, 10))
    stay_context = next(l["text"] for l in brief["front_office"] if l["trace"].startswith("rule"))
    lowered = stay_context.lower()
    assert "would have generated" not in lowered
    assert "would have" not in lowered
    # every sentence in the line starts with a capital, not "this"/"they"
    sentences = [s.strip() for s in stay_context.split(". ") if s.strip()]
    for sentence in sentences:
        first_word = sentence.split()[0]
        assert first_word[0].isupper(), f"sentence does not start uppercase: {sentence!r}"


def test_build_brief_stay_context_cadence_and_priority_wording():
    vip = build_brief(_profile(tier="Gold", visits=4), [],
                      rules={"brief_daily": True, "vip_first": True},
                      sections_cfg={}, today=date(2026, 9, 10))
    vip_line = next(l["text"] for l in vip["front_office"] if l["trace"].startswith("rule"))
    assert "automatic daily VIP brief" in vip_line
    assert "ahead of the regular queue" in vip_line

    on_request = build_brief(_profile(tier="Gold", visits=4), [],
                             rules={"brief_daily": False, "vip_first": True},
                             sections_cfg={}, today=date(2026, 9, 10))
    on_request_line = next(l["text"] for l in on_request["front_office"]
                           if l["trace"].startswith("rule"))
    assert "does not run a daily brief" in on_request_line
